/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  BaseContract,
  BigNumber,
  BigNumberish,
  BytesLike,
  CallOverrides,
  PopulatedTransaction,
  Signer,
  utils,
} from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface TestInterface extends utils.Interface {
  functions: {
    "checkAccess(address,address,uint256)": FunctionFragment;
    "getConcat()": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "checkAccess",
    values: [string, string, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getConcat", values?: undefined): string;

  decodeFunctionResult(
    functionFragment: "checkAccess",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getConcat", data: BytesLike): Result;

  events: {};
}

export interface Test extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: TestInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(
    eventFilter?: TypedEventFilter<TEvent>
  ): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(
    eventFilter: TypedEventFilter<TEvent>
  ): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    checkAccess(
      _patient: string,
      _doctor: string,
      _documentType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    getConcat(overrides?: CallOverrides): Promise<[string]>;
  };

  checkAccess(
    _patient: string,
    _doctor: string,
    _documentType: BigNumberish,
    overrides?: CallOverrides
  ): Promise<boolean>;

  getConcat(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    checkAccess(
      _patient: string,
      _doctor: string,
      _documentType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<boolean>;

    getConcat(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    checkAccess(
      _patient: string,
      _doctor: string,
      _documentType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    getConcat(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    checkAccess(
      _patient: string,
      _doctor: string,
      _documentType: BigNumberish,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    getConcat(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
